# Generated by Django 6.0.5 on 2026-06-03 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_council_id', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(choices=[('Criminal', 'Criminal Law'), ('Civil', 'Civil Law'), ('Cyber', 'Cyber Law'), ('Corporate', 'Corporate Law'), ('Family', 'Family Law'), ('Property', 'Property Law'), ('Consumer', 'Consumer Law'), ('Labor', 'Labor Law'), ('Tax', 'Tax Law'), ('Other', 'Other')], max_length=50)),
                ('experience', models.CharField(choices=[('0-2', '0-2 Years'), ('2-5', '2-5 Years'), ('5-10', '5-10 Years'), ('10-15', '10-15 Years'), ('15+', '15+ Years')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text='Professional introduction', null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('successful_cases', models.IntegerField(default=0)),
                ('bar_council_certificate', models.FileField(blank=True, null=True, upload_to='lawyer_documents/bar_council/')),
                ('llb_certificate', models.FileField(blank=True, null=True, upload_to='lawyer_documents/llb/')),
                ('id_card', models.FileField(blank=True, null=True, upload_to='lawyer_documents/id_card/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='lawyer_profiles/')),
                ('practice_area_proof', models.FileField(blank=True, null=True, upload_to='lawyer_documents/practice/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField()),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_bookings', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lawyer.lawyerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_reviews', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lawyer.lawyerprofile')),
            ],
        ),
    ]
