# Generated by Django 6.0.5 on 2026-06-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('degree', models.CharField(help_text='LLB, LLM, etc.', max_length=200)),
                ('specialization', models.CharField(choices=[('Criminal', 'Criminal Law'), ('Civil', 'Civil Law'), ('Cyber', 'Cyber Law'), ('Corporate', 'Corporate Law'), ('Family', 'Family Law'), ('Property', 'Property Law'), ('Consumer', 'Consumer Law'), ('Labor', 'Labor Law'), ('Tax', 'Tax Law')], max_length=50)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('bio', models.TextField(blank=True, null=True)),
                ('cases_handled', models.TextField(blank=True, help_text='Types of cases handled', null=True)),
                ('bar_council_id', models.CharField(max_length=50, unique=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='lawyer_certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lawyerbooking',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lawyerbooking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='lawyerbooking',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='lawyerbooking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lawyerbooking',
            name='case_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerbooking',
            name='client_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='lawyerbooking',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerbooking',
            name='client_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='lawyerbooking',
            name='case_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lawyerbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyerbooking',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lawyer.lawyer'),
        ),
        migrations.DeleteModel(
            name='LawyerReview',
        ),
        migrations.DeleteModel(
            name='LawyerProfile',
        ),
    ]
