# Generated by Django 6.0.5 on 2026-06-01 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('Cyber Crime', 'Cyber Crime'), ('Consumer Dispute', 'Consumer Dispute'), ('Police Complaint', 'Police Complaint'), ('Land/Property Dispute', 'Land/Property Dispute'), ('Corporate/Legal', 'Corporate/Legal'), ('Other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, null=True)),
                ('evidence_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Under Review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
