# Generated by Django 6.0.5 on 2026-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_complaint_assigned_to_complaint_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='nearest_police_station',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nearest Police Station'),
        ),
    ]
