# Generated by Django 6.0.5 on 2026-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_complaint_nearest_police_station_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='nearest_police_station',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nearest Police Station'),
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
